### ISSUE TITLE
option to change opacity

### ISSUE THREAD

**Issue by varemenos** [braver/method-separator#3]
it would be great to have an option to change the opacity of the line

**Comment by braver** [comment]
The method separator really is just a bit of stylesheet and I'd like to keep it like that. You can look at the stylesheet and for instance copy it to your personal stylesheet to tweak it. Or you can tweak it like this:

```
::shadow .meta.function:before {
  opacity: 1 !important;
}
```

There isn't a clean method for using config variables in a stylesheet. There are some things you can do, but it explodes the complexity of this otherwise very simple package. So, I don't think this is something I would add to this package.
